# Generated by Django 5.0.2 on 2024-03-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='night',
            field=models.IntegerField(default=0),
        ),
    ]
