# Generated by Django 5.0.2 on 2024-03-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_trip_image_alter_trip_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='image',
        ),
    ]
