# Generated by Django 5.0.2 on 2024-03-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_trip_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='image',
        ),
    ]
